language: rust

notifications:
  email:
    on_success: never
    on_failure: always

script:
  - cargo build
  - cargo test
  - cargo doc --no-deps
  - rustdoc --test README.md -L target
  - cargo run --example genkey -- keyfile
  - cargo run --example nss2
  - cargo run --example nss5

after_success:
  - .travis/publish_doc.sh

env:
  global:
    secure: gItlqVnR8TH9C9XFnMkiJnymBK8neHwt5xwGKUwRhQ1u4aiu4j38W6psV+b53N+fomOUeLbxNrbp+zpQTaqC3Ro2fWbp8sXpJIle1shdBbdmgEz5kNvLMWUzGcyjmoVXaj3tRIGdsi0qWiHQM6beq4/Ph02Y68p22BX+2conbH8=
